name: Run petstore collection tests
on:
  push:
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run petstore collection
        run: |
          newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme || true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: testResults
  upload-artifacts:
    runs-on: ubuntu-latest
    needs: test-api
    name: Report publication
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Download artifacts
          uses: actions/download-artifact@v2
        - name: Deploy report to Github pages
          uses: peaceiris/actions-gh-pages@v3
          with: 
            github_token: ${{ secrets.GITHUB_TOKEN}}
            publish_branch: gh-pages
            publish_dir: ./

